language: ruby
cache: bundler
branches:
  only:
    - master
script:
  - ALGOLIA_API_KEY='f8861985314e762b3d9eed7bba54f74e' bundle exec jekyll algolia
  
rvm:
 - 2.4
notifications:
  email:
    on_success: never
    on_failure: never
